[tool.poetry]
name = "single"
version = "0.1.0"
description = ""
authors = ["Erik De Bonte <erikd@microsoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
